-------------- Migration Script ------------------
-- npx ts-node -O '{"module":"commonjs"}' node_modules/typeorm/cli.js -d src/configs/database.ts migration:generate scripts/migrations/LikeCommentOnEventMigrations
-- npx ts-node -O '{"module":"commonjs"}' node_modules/typeorm/cli.js -d src/configs/database.ts migration:run

-------------- Table Creation Query -----------------
-------------- User ---------------
CREATE TABLE "User" (
    "UserId" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "UserName" VARCHAR(30) NOT NULL,
    "Phone" VARCHAR(10) NOT NULL,
    "Email" VARCHAR(100) NOT NULL,
    "Password" VARCHAR(255) NOT NULL
);

-------------- Event ----------------- 
CREATE TABLE "Event" (
    "EventId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(200) NOT NULL,
    "Description" TEXT NOT NULL,
    "Date" DATE NOT NULL,
    "Time" TIME NOT NULL,
    "Location" VARCHAR(255) NOT NULL,
    "Image" VARCHAR(255),
    "Category" VARCHAR(50) NOT NULL,
    "UserId" BIGINT,
    CONSTRAINT "fk_user"
        FOREIGN KEY ("UserId") 
        REFERENCES "User"("UserId") 
        ON DELETE SET NULL
);

---------------- Comment -----------------
CREATE TABLE "Comment" (
    "CommentId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Content" TEXT NOT NULL,
    "EventId" BIGINT,
    "UserId" BIGINT,
    CONSTRAINT "FK_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("EventId") ON DELETE CASCADE,
    CONSTRAINT "FK_User" FOREIGN KEY ("UserId") REFERENCES "User"("UserId") ON DELETE CASCADE
);

---------------- Follow -----------------
CREATE TABLE "Follow" (
    "id" SERIAL PRIMARY KEY,
    "followingId" BIGINT NOT NULL,
    "followerId" BIGINT NOT NULL,
    CONSTRAINT "FK_Following" FOREIGN KEY ("followingId") REFERENCES "User"("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_Follower" FOREIGN KEY ("followerId") REFERENCES "User"("UserId") ON DELETE CASCADE,
    CONSTRAINT "unique_following_follower" UNIQUE ("followingId", "followerId")
);

----------------- UserLikes ------------------
CREATE TABLE "UserLikes" (
    "UserId" BIGINT NOT NULL,
    "EventId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ("UserId", "EventId"),
    CONSTRAINT "FK_UserLikes_User" FOREIGN KEY ("UserId") REFERENCES "User"("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserLikes_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("EventId") ON DELETE CASCADE
);

------------------ Notifications ---------------------
CREATE TABLE "Notifications" (
    "NotificationId" SERIAL PRIMARY KEY,
    "UserId" BIGINT NOT NULL,
    "Type" VARCHAR(50) NOT NULL,
    "Message" TEXT NOT NULL,
    "Read" BOOLEAN DEFAULT FALSE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("UserId") REFERENCES "User"("UserId")
);


