-- npx ts-node -O '{"module":"commonjs"}' node_modules/typeorm/cli.js -d src/configs/database.ts migration:generate scripts/migrations/LikeCommentOnEventMigrations
-- npx ts-node -O '{"module":"commonjs"}' node_modules/typeorm/cli.js -d src/configs/database.ts migration:run

-- Table Creation Query
CREATE TABLE "User" (
    "UserId" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "UserName" VARCHAR(30) NOT NULL,
    "Phone" VARCHAR(10) NOT NULL,
    "Email" VARCHAR(100) NOT NULL,
    "Password" VARCHAR(255) NOT NULL
);

CREATE TABLE "Event" (
    "EventId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(200) NOT NULL,
    "Description" TEXT NOT NULL,
    "Date" DATE NOT NULL,
    "Time" TIME NOT NULL,
    "Location" VARCHAR(255) NOT NULL,
    "Image" VARCHAR(255),
    "Category" VARCHAR(50) NOT NULL,
    "UserId" BIGINT,
    CONSTRAINT "fk_user"
        FOREIGN KEY ("UserId") 
        REFERENCES "User"("UserId") 
        ON DELETE SET NULL
);

